name: states_rebuilder
description: a simple yet powerful state management technique for Flutter

version: 6.3.0+1
homepage: https://github.com/GIfatahTH/states_rebuilder
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  collection: ^1.18.0
  meta: ^1.10.0
  navigation_builder:
    git:
      url: https://github.com/jgfoster/navigation_builder.git
      ref: jgfoster-patch-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: